# -*- coding: utf-8 -*-
"""MMCA Project 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cmSLot-RuWywnevubKBnJ6Ekju3yoj5a
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


print("----- Fitness App User Growth Model -----")

initial_users = int(input("Enter initial number of users: "))
days = int(input("Enter number of days to simulate: "))

retention_rate = float(input("Enter retention rate (0 to 1): "))
churn_rate = float(input("Enter churn rate (0 to 1): "))
new_user_ratio = float(input("Enter new user ratio (0 to 1): "))



data = []
current_users = initial_users

for day in range(days):

    retained_users = current_users * retention_rate
    dropouts = current_users * churn_rate
    new_users = current_users * new_user_ratio

    predicted_users = retained_users + new_users - dropouts

    data.append([
        day + 1,
        current_users,
        new_users,
        retained_users,
        dropouts,
        predicted_users
    ])

    current_users = predicted_users



df = pd.DataFrame(data, columns=[
    "Day",
    "Current Users",
    "New Users",
    "Retained Users",
    "Dropouts",
    "Predicted Users"
])

print("\n===== MODEL OUTPUT =====")
print(df)


df.to_csv("fitness_growth_output.csv", index=False)


plt.figure()
plt.plot(df["Day"], df["Current Users"], label="Current Users")
plt.plot(df["Day"], df["Predicted Users"], label="Predicted Users")
plt.legend()
plt.xlabel("Days")
plt.ylabel("Users")
plt.title("User Growth Prediction")
plt.show()


plt.figure()
plt.plot(df["Day"], df["New Users"])
plt.xlabel("Days")
plt.ylabel("Users")
plt.title("New Users Growth")
plt.show()


plt.figure()
plt.plot(df["Day"], df["Retained Users"])
plt.xlabel("Days")
plt.ylabel("Users")
plt.title("Retained Users")
plt.show()


plt.figure()
plt.plot(df["Day"], df["Dropouts"])
plt.xlabel("Days")
plt.ylabel("Users")
plt.title("User Dropouts")
plt.show()


plt.figure()
plt.plot(df["Day"], df["New Users"], label="New Users")
plt.plot(df["Day"], df["Retained Users"], label="Retained Users")
plt.plot(df["Day"], df["Dropouts"], label="Dropouts")
plt.legend()
plt.xlabel("Days")
plt.ylabel("Users")
plt.title("User Components Analysis")
plt.show()

